### ISSUE TITLE
Android 4.4 崩溃

### ISSUE THREAD

**Issue by hgraceb** [bytedance/BoostMultiDex#11]
## 问题

1. 在API 19（Android 4.4）上，使用笔者的应用以及官方下载的抖音应用进行测试，进入应用一段时间后都会崩溃。

2. 是否有兼容的方案？比如说控制`main dex`或者`second dex`的方法数上限。

3. 尝试使用`--set-max-idx-number`选项设置，但是此选项只对`DX`编译器有用，目前本人项目中使用`Gradle`版本为`3.5.3`（`AndroidX`对`Gradle`的版本有要求，无法降级`Gradle`到默认使用`DX`编译器的版本），默认使用的是`D8`编译器，使用`android.enableD8=false`之后，`--set-max-idx-number`选项还是不生效。是否有其他方案？

## 抖音版本

`aweme_aweGW_v110901_6502_1594721527`（http://s.toutiao.com/UsMYE/ 下载的）

## 崩溃信息

安装抖音之后，在控制台没有看到`BoostMultiDex`相关的日志信息，猜测是抖音屏蔽了日志输出，以下是笔者的`debug`应用安装后输出的日志信息。

```powershell
07-16 01:16:03.314 I/BoostMultiDex: BoostMultiDex is installing, version is 1.0.1
07-16 01:16:03.314 I/BoostMultiDex: VM with version 1.6.0 does not have support
07-16 01:16:03.324 I/BoostMultiDex: Do checksum true
07-16 01:16:03.324 I/BoostMultiDex: Blocking on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:03.324 I/BoostMultiDex: Acquired on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:03.324 I/BoostMultiDex: Blocking on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.install.lock
07-16 01:16:03.324 I/BoostMultiDex: Acquired on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.install.lock
07-16 01:16:03.324 I/BoostMultiDex: Released lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:03.424 I/BoostMultiDex: VM lib is libdvm.so
07-16 01:16:03.424 I/BoostMultiDex: Memory remains 83927040, free space 2465812480
07-16 01:16:03.424 I/BoostMultiDex: Extracting /data/data/com.test.packagename/files/boost_multidex/dex_cache/tmp-15477232752.dex
07-16 01:16:03.774 I/BoostMultiDex: Renaming to /data/data/com.test.packagename/files/boost_multidex/dex_cache/2.dex
07-16 01:16:03.794 I/BoostMultiDex: Put f key dex.checksum.dex.time.2 checksum=75797446, time=1594883763000
07-16 01:16:03.804 I/BoostMultiDex: Memory remains 83927040, free space 2455855104
07-16 01:16:03.804 I/BoostMultiDex: Extracting /data/data/com.test.packagename/files/boost_multidex/dex_cache/tmp--10598086823.dex
07-16 01:16:04.154 I/BoostMultiDex: Renaming to /data/data/com.test.packagename/files/boost_multidex/dex_cache/3.dex
07-16 01:16:04.194 I/BoostMultiDex: Put f key dex.checksum.dex.time.3 checksum=2531167225, time=1594883764000
07-16 01:16:04.304 I/BoostMultiDex: Memory remains 83927040, free space 2445991936
07-16 01:16:04.304 I/BoostMultiDex: Extracting /data/data/com.test.packagename/files/boost_multidex/dex_cache/tmp-1020745524.dex
07-16 01:16:04.334 I/BoostMultiDex: Renaming to /data/data/com.test.packagename/files/boost_multidex/dex_cache/4.dex
07-16 01:16:04.334 I/BoostMultiDex: Put f key dex.checksum.dex.time.4 checksum=1244119903, time=1594883764000
07-16 01:16:04.994 I/BoostMultiDex: Load dex in holder com.bytedance.boost_multidex.DexHolder$DexBuffer@41fcfc78, index: 2, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/2.dex, size: 9945892], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/2.odex, size: 0]
07-16 01:16:04.994 I/BoostMultiDex: Add info: com.bytedance.boost_multidex.DexHolder$DexBuffer@41fcfc78, index: 2, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/2.dex, size: 9945892], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/2.odex, size: 0]
07-16 01:16:05.574 I/BoostMultiDex: Load dex in holder com.bytedance.boost_multidex.DexHolder$DexBuffer@41fd9e28, index: 3, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/3.dex, size: 9873536], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/3.odex, size: 0]
07-16 01:16:05.574 I/BoostMultiDex: Add info: com.bytedance.boost_multidex.DexHolder$DexBuffer@41fd9e28, index: 3, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/3.dex, size: 9873536], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/3.odex, size: 0]
07-16 01:16:05.624 I/BoostMultiDex: Load dex in holder com.bytedance.boost_multidex.DexHolder$DexBuffer@41fe4060, index: 4, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/4.dex, size: 933880], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/4.odex, size: 0]
07-16 01:16:05.624 I/BoostMultiDex: Add info: com.bytedance.boost_multidex.DexHolder$DexBuffer@41fe4060, index: 4, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/4.dex, size: 933880], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/4.odex, size: 0]
07-16 01:16:05.624 D/BoostMultiDex: After install all, sp value is {dex.obj.type2=1, dex.obj.type3=1, dex.number=4, dex.checksum.3=2531167225, dex.obj.type4=1, dex.checksum.2=75797446, dex.time.2=1594883763000, timestamp=1594883622000, dex.time.3=1594883764000, dex.time.4=1594883764000, crc=4060231304, dex.checksum.4=1244119903}
07-16 01:16:05.624 I/BoostMultiDex: Released lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.install.lock
07-16 01:16:05.634 I/BoostMultiDex: install done
07-16 01:16:18.154 I/BoostMultiDex: BoostMultiDex is installing, version is 1.0.1
07-16 01:16:18.154 I/BoostMultiDex: VM with version 1.6.0 does not have support
07-16 01:16:18.154 I/BoostMultiDex: Do checksum true
07-16 01:16:18.154 I/BoostMultiDex: VM lib is libdvm.so
07-16 01:16:20.124 I/BoostMultiDex: Install holder: com.bytedance.boost_multidex.DexHolder$ApkBuffer, index 0
07-16 01:16:20.734 I/BoostMultiDex: Install holder: com.bytedance.boost_multidex.DexHolder$ApkBuffer, index 1
07-16 01:16:20.784 I/BoostMultiDex: Install holder: com.bytedance.boost_multidex.DexHolder$ApkBuffer, index 2
07-16 01:16:21.124 D/BoostMultiDex: Starting OptimizeService
07-16 01:16:31.134 I/BoostMultiDex: Blocking on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.install.lock
07-16 01:16:31.134 I/BoostMultiDex: Acquired on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.install.lock
07-16 01:16:31.154 I/BoostMultiDex: Process beginning holder com.bytedance.boost_multidex.DexHolder$DexBuffer@42410c88, index: 2, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/2.dex, size: 9945892], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/2.odex, size: 0], type: 1
07-16 01:16:31.154 I/BoostMultiDex: Free space is enough: 2440122368, continue...
07-16 01:16:31.154 D/BoostMultiDex: Process holder, com.bytedance.boost_multidex.DexHolder$DexBuffer@42410c88, index: 2, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/2.dex, size: 9945892], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/2.odex, size: 0]
07-16 01:16:33.554 W/BoostMultiDex: Opt dex in origin way
07-16 01:16:35.764 E/BoostMultiDex: Fail to opt dex finally
    java.io.IOException: unable to open DEX file
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:296)
        at dalvik.system.DexFile.<init>(DexFile.java:111)
        at dalvik.system.DexFile.loadDex(DexFile.java:151)
        at com.bytedance.boost_multidex.DexHolder$DexBuffer.toFasterHolder()
        at com.bytedance.boost_multidex.OptimizeService.handleOptimize()
        at com.bytedance.boost_multidex.OptimizeService.onHandleIntent()
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-16 01:16:35.774 I/BoostMultiDex: Blocking on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:35.774 I/BoostMultiDex: Acquired on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:35.774 I/BoostMultiDex: Released lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:35.774 I/BoostMultiDex: Process beginning holder com.bytedance.boost_multidex.DexHolder$DexBuffer@42414258, index: 3, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/3.dex, size: 9873536], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/3.odex, size: 0], type: 1
07-16 01:16:35.774 I/BoostMultiDex: Free space is enough: 2430173184, continue...
07-16 01:16:35.774 D/BoostMultiDex: Process holder, com.bytedance.boost_multidex.DexHolder$DexBuffer@42414258, index: 3, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/3.dex, size: 9873536], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/3.odex, size: 0]
07-16 01:16:38.274 W/BoostMultiDex: Opt dex in origin way
07-16 01:16:40.654 E/BoostMultiDex: Fail to opt dex finally
    java.io.IOException: unable to open DEX file
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:296)
        at dalvik.system.DexFile.<init>(DexFile.java:111)
        at dalvik.system.DexFile.loadDex(DexFile.java:151)
        at com.bytedance.boost_multidex.DexHolder$DexBuffer.toFasterHolder()
        at com.bytedance.boost_multidex.OptimizeService.handleOptimize()
        at com.bytedance.boost_multidex.OptimizeService.onHandleIntent()
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
07-16 01:16:40.654 I/BoostMultiDex: Blocking on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.654 I/BoostMultiDex: Acquired on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.654 I/BoostMultiDex: Released lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.664 I/BoostMultiDex: Process beginning holder com.bytedance.boost_multidex.DexHolder$DexBuffer@424171c8, index: 4, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/4.dex, size: 933880], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/4.odex, size: 0], type: 1
07-16 01:16:40.664 I/BoostMultiDex: Free space is enough: 2420289536, continue...
07-16 01:16:40.664 D/BoostMultiDex: Process holder, com.bytedance.boost_multidex.DexHolder$DexBuffer@424171c8, index: 4, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/4.dex, size: 933880], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/4.odex, size: 0]
07-16 01:16:40.964 I/BoostMultiDex: Put o key odex.checksum.odex.time.4 checksum=1000808, time=1594883800000
07-16 01:16:40.974 D/BoostMultiDex: Put info, 4 file is /data/data/com.test.packagename/files/boost_multidex/odex_cache/4.odex
07-16 01:16:40.974 I/BoostMultiDex: Cost time: 311412917, free space: 2420289536, reduced space: -1003520, holder: com.bytedance.boost_multidex.DexHolder$DexOpt@424189f0, index: 4, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/4.dex, size: 933880], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/4.odex, size: 1000808], force: false
07-16 01:16:40.974 I/BoostMultiDex: Blocking on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.974 I/BoostMultiDex: Acquired on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.974 I/BoostMultiDex: Released lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.974 I/BoostMultiDex: Free space is enough: 2419286016, continue...
07-16 01:16:40.974 D/BoostMultiDex: Process holder, com.bytedance.boost_multidex.DexHolder$DexOpt@424189f0, index: 4, [file: /data/data/com.test.packagename/files/boost_multidex/dex_cache/4.dex, size: 933880], [opt file: /data/data/com.test.packagename/files/boost_multidex/odex_cache/4.odex, size: 1000808], force: false
07-16 01:16:40.974 I/BoostMultiDex: Blocking on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.974 I/BoostMultiDex: Acquired on lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.974 I/BoostMultiDex: Released lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.prepare.lock
07-16 01:16:40.974 I/BoostMultiDex: Released lock /data/data/com.test.packagename/files/boost_multidex/boost_multidex.install.lock
07-16 01:16:40.984 I/BoostMultiDex: Exit quietly
```

## 机型信息（Testin上进行测试）

- 品牌 samsung
- 别名 Galaxy Grand Prime
- 型号 SM-G5308W
- 系统 android4.4.4
- 屏幕尺寸 5
- 分辨率 960*540
- CPU 高通 骁龙410（MSM8916）
- 核心数 4
- 主频 1.2
- RAM 0.9 GB

**Comment by GalaxyLeo** [comment]
谢谢反馈。这个有crash的堆栈吗？上面贴日志的不是最终crash的地方
另外，用官方MultiDex是正常起来的吗？

**Comment by hgraceb** [comment]
已解决，感谢！

相关Issue：[https://github.com/Tencent/tinker/issues/925#issuecomment-500123970](https://github.com/Tencent/tinker/issues/925#issuecomment-500123970)

解决方案：[https://github.com/cantalou/DexOptFix](https://github.com/cantalou/DexOptFix)
